os: osx
language: swift
osx_image: xcode10.1
xcode_project: BeaconChain.xcodeproj
xcode_scheme: BeaconChain.Package

jobs:
  fast_finish: true
  include:
    - script: make test
    - script:
        - make xcode
        - make lint
      env: ALLOW_FAILURE=true
  allow_failures:
    - env: ALLOW_FAILURE=true

notifications:
  email: false
